@id("b3a4fd8c-55c5-4c39-98f6-59a46c4638ec")
@nodeType("BaseNodeTypes:::SQLWork")
SELECT
     "PRODUCT_ID" AS "PRODUCT_ID",
     "PRODUCT_NAME" AS "PRODUCT_NAME",
     "CATEGORY" AS "CATEGORY",
     "PRICE" AS "PRICE",
     "QUANTITY" AS "QUANTITY"
FROM {{ ref('SRC', 'SOURCE_PRODUCT_ANALYTICS') }} "SOURCE_PRODUCT_ANALYTICS"